SET DATABASE SQL SYNTAX ORA TRUE;

CREATE TABLE USERS(
	ID bigint generated by default as identity (start with 3),
	NAME varchar(255),
	LASTNAME varchar(255),
	EMAIL varchar(255) NOT NULL,
	PASSWORD varchar(255) NOT NULL,
	JOB varchar(255),
	ROLE varchar(255) NOT NULL,
	primary key (ID));

CREATE TABLE ADDRESSES(
	ID bigint generated by default as identity (start with 33),
	DELETED NUMBER(1,0),
	CITY varchar(255) NOT NULL,
	TOWN varchar(255) NOT NULL,
	DISTRICT varchar(255) NOT NULL,
	primary key (ID));

CREATE TABLE SECTORS(
	ID bigint generated by default as identity (start with 1),
	DELETED NUMBER(1,0) DEFAULT 0,
	NAME varchar(255) NOT NULL,
	IMAGE varchar(255),
	ALT varchar(255),
	primary key (ID));

CREATE TABLE APPOINTMENTS(
	ID bigint generated by default as identity (start with 14),
	DELETED NUMBER(1,0) DEFAULT 0,
	NAME varchar(255) NOT NULL,
	SECTOR varchar(255) NOT NULL,
	CITY varchar(255) NOT NULL,
	TOWN varchar(255) NOT NULL,
	DISTRICT varchar(255) NOT NULL,
	STATUS varchar(255) NOT NULL,
	IMAGE varchar(255),
	primary key (ID));
